name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable --check-cache --check-resolutions

      - name: Check yarn dedupe
        run: yarn dedupe --check

      - name: Run prettier
        run: yarn run fmt:check

      - name: Run eslint
        run: yarn run lint

      - name: Build project
        run: yarn run build
